### ISSUE TITLE
`paper_results.ipynb` figures are broken, not possible to reproduce results

### ISSUE THREAD

**Issue by remo-help** [KietzmannLab/EmergentPredictiveCoding#2]
Hi,

I'm trying to reproduce the results of this paper and I'm running into some issues with your notebook. Looks like the figures are broken.

'Figure 2A' in the notebook references a function from the `plot.py` file called `bootstrap_model_activity()`. This function does not exist in `plot.py`. There is a function with this name in `helper.py`. but it does not produce a plot.

It also appears that the function which should produce Figure 2B (`plot.example_sequence_state()` has the lines commented out which actually produce the figure.

The function which is supposed to generate Figure 3A (`plot.scatter_units()`) does not exist in any of the files of the repo.

Figure 3B is broken because the wrong arguments are referred to in the notebook, I can't figure out what the actual arguments are supposed to be.

I didnt bother testing the rest. It appears to me that this notebook was compiled with a completely different repo? I'm not sure what happened here exactly. Can you please try to run your notebook within your repo or point me to the repo with which this was actually compiled?

Thanks!
-Remo

**Comment by AbdullahiAli** [comment]
Hi, thank you for you catching this. The notebook is from the original preprint and should be removed.  For now, I recommend you to look at https://osf.io/c57d4/wiki/home/ which should have the correct instructions.

**Comment by twhume** [comment]
I hit the same problem with the notebook.

(also noticed that train.py doesn't seem to create exactly the same models the notebook needs)

Thanks for the pointer to the OSF site; but I can't see any instructions there for doing an evaluation of the trained networks. Is there an alternative notebook or another mechanism for checking this?

**Comment by remo-help** [comment]
@twhume The models are the same, they're just produced in a wonky directory structure. 

For the evaluation, you need to run the `fig*.py` files and point them at the directories your `train.py` produced. 

I think you also need to create the directories first or you might get an error on Linux based OS

**Comment by AbdullahiAli** [comment]
@twhume best to ignore the notebook, there are trained models available for eval. I'll close this issue for now, but feel free to hit me up at abdullahi.ali@donders.ru.nl if you need help setting up training. Same holds for you @remo-help in case you need it.
